version: '2.1'

services:
  kong:
    build: .
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PORT=5432
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
      - KONG_PLUGIN_PATH=/kong-plugins
      - KONG_LOG_LEVEL=info
      - KONG_CUSTOM_PLUGINS=wsse
      - KONG_NGINX_DAEMON=off
      - LUA_PATH=/kong-plugins/?.lua;/kong-plugins/?/init.lua;;
      - KONG_ADMIN_ACCESS_LOG=/proc/1/fd/1
      - KONG_ADMIN_ERROR_LOG=/proc/1/fd/2
      - KONG_PROXY_ACCESS_LOG=/proc/1/fd/1
      - KONG_PROXY_ERROR_LOG=/proc/1/fd/2
      - LUAROCKS_API_KEY=${LUAROCKS_API_KEY}
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10
    volumes:
      - .:/kong-plugins
      - ./spec/kong_tests.conf:/kong/spec/kong_tests.conf
    command: bash -c "/kong/bin/kong migrations up && /kong/bin/kong start -v"

  kong-database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data:rw
